language: rust
osx_image: xcode8.2

rust:
  - stable
  - nightly

os:
  - linux
  - osx

install:
 - if [ "$TRAVIS_OS_NAME" == "osx" ]; then wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;bash miniconda.sh -b -p $HOME/miniconda; export PATH="$HOME/miniconda/bin:$PATH" ;  fi

matrix:
  allow_failures:
    - rust: nightly

cache:
  directories:
    - $HOME/.cargo

script:
  - cd rust
  - export CARGO_TARGET_DIR=/tmp/target
  - cargo build || exit
  - cargo build --manifest-path syntect-plugin/Cargo.toml || exit
  - for MANIFEST in Cargo.toml */Cargo.toml; do cargo test --manifest-path $MANIFEST || exit; done

language: python
python:
  - "3.5"
script: python setup.py install &&  pytest python/tests