sudo: required
language: rust
rust:
  - stable
  - nightly
python:
  - "3.5"
os:
  - linux
  - osx
matrix:
  allow_failures:
    - rust: nightly
cache:
  directories:
    - $HOME/.cargo
env:
  $PYTHON=python3.5
before_install: |
  if [ "$TRAVIS_OS_NAME" == "osx" ]; then
    brew update
    brew install python3.5
    alias python=python3.5
    brew outdated pyenv || brew upgrade pyenv
    brew install pyenv-virtualenv
    pyenv install $PYTHON
    export PYENV_VERSION=$PYTHON
    export PATH="/Users/travis/.pyenv/shims:${PATH}"
    pyenv-virtualenv venv
    source venv/bin/activate
    python --version
  fi

  if [ "$TRAVIS_OS_NAME" == "linux" ]; then
    sudo apt-get update
    sudo apt-get install python3.5
    alias python=python3.5
    sudo apt-get -y install python3-pip python-dev
    sudo pip3 install -U setuptools
    sudo pip3 install -U virtualenvwrapper
    python -V
    pip -V
  fi

install:
  - alias python=python3.5
  - sudo python -m pip install -U pip
  - sudo pip install pytest
script:
  - alias python=python3.5
  - python --version
  - cd rust
  - export CARGO_TARGET_DIR=/tmp/target
  - cargo build || exit
  - cargo build --manifest-path syntect-plugin/Cargo.toml || exit
  - for MANIFEST in Cargo.toml */Cargo.toml; do cargo test --manifest-path $MANIFEST || exit; done
  - python setup.py install
  - python -m pytest python/tests
