sudo: required
language: rust
rust:
  - stable
  - nightly
python:
  - "3.5"
os:
  - linux
  - osx
matrix:
  allow_failures:
    - rust: nightly
cache:
  directories:
    - $HOME/.cargo

before_install: |
  if [ "$TRAVIS_OS_NAME" == "osx" ]; then
    brew update
    brew install python3.5

    brew outdated pyenv || brew upgrade pyenv
    brew install pyenv-virtualenv
    pyenv install 3.5
    export PYENV_VERSION=3.5
    export PATH="/Users/travis/.pyenv/shims:${PATH}"
    pyenv-virtualenv venv
    source venv/bin/activate
    python --version

  else
    sudo apt-get update
    sudo apt-get install python3.5
    sudo apt-get -y install python3-pip python-dev
    sudo pip3 install -U setuptools
    sudo pip3 install -U virtualenvwrapper
    python3 -V
    pip3 -V
  fi

install:
  - alias python=python3.5
  - sudo python3 -m pip3 install -U pip3
  - sudo pip3 install pytest
script:
  - python3 --version
  - cd rust
  - export CARGO_TARGET_DIR=/tmp/target
  - cargo build || exit
  - cargo build --manifest-path syntect-plugin/Cargo.toml || exit
  - for MANIFEST in Cargo.toml */Cargo.toml; do cargo test --manifest-path $MANIFEST || exit; done
  - python3 setup.py install
  - python3 -m pytest python/tests
